description: finetuning test on AMLK8s

target:
  service: amlk8s
  name: ms-shared-v100

environment:
  image: sonichi/hpo4hf:latest
  setup:
    # - pip install transformers datasets wandb prompt_toolkit==1.0.14 --user
    # - sudo apt-get -y install git
    - git clone https://github.com/liususan091219/FLAML.git
    - cd FLAML
    - git checkout exp
    - pip install -e.[blendsearch,ray] --user
    - export WANDB_API_KEY=7553d982a2247ca8324ec648bd302678105e1058

code:
  local_dir: $CONFIG_DIR/../

jobs:
